version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started on `date`
      - node -v
      - npm install
artifacts:
  files:
    - '**/*'
